freebsd_instance:
  image_family: freebsd-13-0-snap

task:
  env:
    matrix:
      - LISP: sbcl
      - LISP: ccl
  preinstall_script:
    - pkg install -y curl git blas lapack
  install_script:
    - curl -L https://raw.githubusercontent.com/shamazmazum/cl-cirrus/master/install.sh | sh
    - git clone --depth=1 git://github.com/shamazmazum/codex.git ~/lisp/codex
    - git clone --depth=1 git://github.com/shamazmazum/docparser.git ~/lisp/docparser
  script:
    - cl -l neural-classifier -e '(uiop:quit)'
    # - cl -l codex -e '(codex:document :neural-classifier :skip-undocumented t)'
