freebsd_instance:
  image_family: freebsd-13-0-snap

task:
  env:
    matrix:
      - LISP: sbcl
      - LISP: ccl
  preinstall_script:
    - pkg install -y curl git blas lapack
  install_script:
    - curl -L https://raw.githubusercontent.com/shamazmazum/cl-cirrus/master/install.sh | sh
  ultralisp_script:
    - cl -e '(ql-dist:install-dist "http://dist.ultralisp.org/" :prompt nil)'
  mnist_script:
    - git submodule update --init
    - cd mnist/dataset && gunzip -k *.gz
  script:
    - cl -l neural-classifier -f tests/actions.lisp
