language: common-lisp

env:
  global:
    secure: "N8sb7mYlsjup92hF4Ae5WqyHa+PTSNtH+YlvkwBJhIEPj9zZgeXEBG/kddNRX703IqdQovsk09SdWGtMUgzANBz8gHbE92WWeV90YuY9aMG9toF2f8IxMg8AkftUw6YWx8bBu7V5UlkIJPsnIZJZmk0BsrLKKSrqPzUC7IRIO/f1PPGhc8YmUQln6EMuBZy8HfOAIM+a/dLdZie/1tyhWVmgD3BGji2EbcqW5YLUNvPpxxgqLoB8ZzEi33BUcrjnY1oIHYV29paQax7IWvquyNss5b/KKIXQb32vnHGgKiH24Sy8v60IxsRxhBkeYJchjk9WzXF2HIcGCt3+AVT4VzSqBx4CszrdiVMv9DnQW7V7BipeN46YUrGfOukZsimiqWE2iVjdxAtH78ZG+yaS6bcOHH8PwNOLVmUhqtDHfLNVC87vDFCudzLShhQ8/9WyPWgHZt4SfKGV/9iirpS11fJRxaNfA3k/FNPkYK2jNG/X917xI/RIrsZ/Dm1NCsPZuzMchPxysG5owSHZDrreNcqrQN2TF62CNi7r9KnGafvXEgV4gtF8RLm06Jx15M29xtpy1X992iFij4lP9c/Q7pNR/PDUngN4dV95lN9Gu8+qiXtCI/Hb0dSp1ZdisYEYhb+QM7kQ14flvjTM4l9p5wkI9Q4Emg+wnkqw0OqXDkM="
  matrix:
    - LISP=sbcl

install:
  - sudo apt-get install info install-info libblas-dev liblapack-dev
  - curl https://raw.githubusercontent.com/luismbo/cl-travis/master/install.sh | sh;
  - git clone --depth=1 git://github.com/shamazmazum/codex.git ~/lisp/codex
  - git clone --depth=1 git://github.com/shamazmazum/docparser.git ~/lisp/docparser
  - cl -e '(ql-util:without-prompting (ql:add-to-init-file))'

script:
  - cl -l neural-classifier -e '(uiop:quit)'
  - cl -l codex -e '(codex:document :neural-classifier :skip-undocumented t)'

deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  keep_history: true
  local_dir: "$TRAVIS_BUILD_DIR/docs/build/neural-classifier/html"
  edge: true
  on:
    branch: master
