name: Tests

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      LISP: sbcl
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install dependencies
        run: |
          sudo apt-get install info install-info libblas-dev liblapack-dev
      - name: Install CIM and Ultralisp
        run: |
          curl -L https://raw.githubusercontent.com/shamazmazum/cl-cirrus/github-actions/install-actions.sh | sh
          cl -e '(ql-dist:install-dist "http://dist.ultralisp.org/" :prompt nil)'
      - name: Build
        run: |
          cl -l neural-classifier -e '(uiop:quit)'
      - name: Run tests
        run: |
          cd $GITHUB_WORKSPACE/mnist/dataset && gunzip *gz
          cl -f $GITHUB_WORKSPACE/tests/actions.lisp
